# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'slamApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit', '~> 3.0.0'

pod 'ReactiveSwift', '~> 3.0'
pod 'ReactiveCocoa', '~> 7.0'
pod 'CocoaMQTT'
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'

end
